# Generated by Django 3.2.7 on 2021-09-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDRdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MSISDN', models.IntegerField(max_length=100)),
                ('CALL_ORIG_NUM', models.IntegerField(max_length=100)),
                ('CALL_DIALED_NUM', models.IntegerField(max_length=100)),
                ('IMSI', models.IntegerField(max_length=100)),
                ('IMEI', models.IntegerField(max_length=100)),
                ('CALL_START_DT_TM', models.DateTimeField(max_length=100)),
                ('CALL_END_DT_TM', models.DateTimeField(max_length=100)),
                ('INBOUND_OUTBOUND_IND', models.CharField(max_length=100)),
                ('Call_Network_Volume', models.CharField(max_length=100)),
                ('Cell_Lac_Id', models.CharField(max_length=100)),
                ('Cell_Site_Id', models.CharField(max_length=100)),
                ('LAT', models.CharField(max_length=100)),
                ('LONGITUDE', models.CharField(max_length=100)),
                ('CALL_TYPE', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
